version: "3.5"
networks:
  mcf:
    name: "mcf"
    external: true
services:
  project-b:
    build:
      context: ../project
      dockerfile: ./Dockerfile
    environment:
      NAME: 'project-b'
      PORT: 8080
      PROXY_FROM: http://project-a:8080
    networks:
    - mcf
  db-ensure:
    build:
      context: ../db-ensure
      dockerfile: ./Dockerfile
    environment:
      DB_MAKER_ADDRESS: http://db-maker:2222
      DB_MAKER_DB_HOST: mysql
      DB_MAKER_DB_NAME: project_b
      DB_MAKER_DB_USER: proj_b_user
      DB_MAKER_DB_PASSWORD: proj_b_password
    networks:
    - mcf
